FROM python:3.11-slim
WORKDIR /app
COPY etl/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY etl /app/etl
COPY sql /app/sql
ENV PYTHONUNBUFFERED=1
CMD ["python", "-m", "etl.main", "run"]
